---
galaxy_info:
  role_name: rhel10-stig
  author: TBD
  description: Applies RHEL 10 STIG V1R1 hardening controls
  company: TBD
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "10"
  galaxy_tags:
    - security
    - hardening
    - stig
    - rhel
    - rhel10
dependencies: []
